### ISSUE TITLE
Crash when launching

### ISSUE THREAD

**Issue by Flnchie** [Minenash/SoulGuard#2]
https://pastebin.com/4WJ1hFyU

**Comment by Minenash** [comment]
Are you sure it only happens if this mod is in, because the error shows names of like 6 mods (which I think is the most I've ever seen in a single error, that must be a record), none of which is SoulGuard. I think the best starting point would probably be to report to the author of diagonalblocks

**Comment by Flnchie** [comment]
only if this mod is in, our pack runs fine without it.

**Comment by Minenash** [comment]
Hmm, which launcher are you using?

**Comment by Minenash** [comment]
Just to be clear, I don't think it's the launcher's fault, but I'm wondering if the error that's actually crashing the game is even in the log. As some launchers like Modrinth's have the crashes in a separate file for some reason

**Comment by Flnchie** [comment]
It's on modrinth yeah, it didnt generate a crash report so i had to grab the logs instead

**Comment by Minenash** [comment]
Can you include the crash that's located in the "crash report" folder instead of the "logs" folder?

**Comment by Flnchie** [comment]
it didnt make a crash report

**Comment by Minenash** [comment]
Hmm, can you provide the modpack you're using so I can debug tomorrow night?

**Comment by Flnchie** [comment]
[Cobblemon Fabric * Fortune](https://modrinth.com/modpack/cff/versions)
This one includes craft tweaker, which seems to cause a crash with soulguard, but even after removal it still wont launch
